### PR TITLE
Adds DB Models and User Creation/Login Session Handling

### PR DESCRIPTION
**Pull request by Step7750**
* Uses bcrypt password hashing
* Handles user sessions with `express-sessions`
* Ensures valid DB field structure and that the case insensitive username and email are unique
* Uses `sqlite` for now just to simplify things, it can be easily switched out in the config.

### CODE REVIEW

**Comment by Step7750** [comment]
@xiningchen 
`name` is the form in the URL and short name 
`title` is the form that is shown to users as the human readable name

ex. name = "bcc" and title = "Bitconnect"
In the URL it'll be something like meme.place/p/bcc but when the community name is shown to the user, it'll be "Bitconnect" throughout the UI.

This is mostly required due to spaces and special characters in the community name. If we used the title in the URL, there'd be issues with escaping and it'd be longer. As a result, the `name` is heavily restricted to only alphanumeric strings with max-len of 25 while name is any string with a max-len of 100

**Comment by Step7750** [comment]
For the community creator, yes, I'd imagine they'd have the power to delete comments/memes in their community since they'd also be able to delegate moderators that can delete comments and/or memes.

**Comment by xiningchen** [comment]
Another question: Are all communities (when created) public? Or can people create private communities so that they can control who joins?

**Comment by Step7750** [comment]
Yes, currently all created communities are public.

**Pull request merged**
